services:
  - type: web
    name: django-portfolio
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
          libjpeg-dev \
          zlib1g-dev \
          libfreetype6-dev \
          liblcms2-dev \
          libopenjp2-7-dev \
          libtiff5-dev \
          libwebp-dev \
          && pip install -r requirements.txt \
          && python manage.py collectstatic --no-input \
          && python manage.py migrate
    startCommand: python manage.py runserver 0.0.0.0:$PORT