# Generated by Django 5.0.6 on 2024-06-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_about_category_home_portfolio_profile_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
